{
  description = "A collection of overlays, modules, libs, and templates for working with dinix";

  outputs =
    { self }:
    let
      sources = import ./lon.nix;
      defaultPkgs = system: import sources.nixpkgs { inherit system; };

      dinixSystem =
        {
          system ? builtins.currentSystem,
          pkgs ? null,
          nixpkgs ? null,
          lib ? null,
          specialArgs ? { },
          modules ? [ ],
          ...
        }:
        let
          resolvedPkgs =
            if pkgs != null then
              pkgs
            else if nixpkgs != null then
              nixpkgs.legacyPackages.${system}
            else
              defaultPkgs system;
          resolvedLib = if lib != null then lib else resolvedPkgs.lib;
          config = resolvedLib.evalModules {
            class = "nixos";
            specialArgs = specialArgs // {
              inherit resolvedPkgs;
              pkgs = resolvedPkgs;
              # Keep compatibility with hardware-configuration.nix files
              # generated by nixos-generate-config.
              modulesPath = "${resolvedPkgs.path}/nixos/modules";
              modules = self.nixosModules;
            };
            # The default set contains the foundational modules. Import the
            # auto-discovered program and service modules as well so public
            # flake configurations can use options such as nix.*, Hyprland,
            # NetworkManager, and nix-daemon without importing them manually.
            modules = lib.unique (lib.attrValues self.nixosModules) ++ [
              { nixpkgs.pkgs = resolvedPkgs; }
            ] ++ modules;
          };
        in
        config
        // {
          inherit resolvedPkgs resolvedLib;
          pkgs = resolvedPkgs;
          lib = resolvedLib;
        };
    in
    {
      nixosModules = import ./modules;

      # Reusable constructor for consumers that want to define their own
      # nixosConfigurations in a separate flake.
      lib.dinixSystem = dinixSystem;

      formatter =
        let
          sources = import ./lon.nix;
          lib = import (sources.nixpkgs + "/lib");

          pkgsFor = system: import sources.nixpkgs { inherit system; };
        in
        lib.genAttrs' [ "aarch64-linux" "x86_64-linux" ] (
          system: lib.nameValuePair system (pkgsFor system).nixfmt-tree
        );
    };
}
