{ config, lib, ... }:
{
  options.nixpkgs = {
    # Keep compatibility with hardware-configuration.nix files generated by
    # nixos-generate-config.  Dinix receives an already-evaluated package set
    # through dinixSystem, so this is metadata rather than a second package-set
    # selection mechanism.
    hostPlatform = lib.mkOption {
      type = lib.types.str;
      default = config.nixpkgs.pkgs.stdenv.hostPlatform.system;
      description = "The platform targeted by this system configuration.";
    };

    pkgs = lib.mkOption {
      type = lib.types.pkgs // {
        description = "An evaluation of Nixpkgs; the top level attribute set of packages";
      };
      description = ''
        The `nixpkgs` package set to use for this system.
      '';
    };
  };

  config = {
    _module.args = {
      pkgs = config.nixpkgs.pkgs;
    };
  };
}
